//
//  MUKConsts.m
//  MpegUrlKit
//
//  Created by Hinagiku Soranoba on 2017/01/06.
//  Copyright © 2017年 Hinagiku Soranoba. All rights reserved.
//

#import "MUKConsts.h"
#import "MUKErrorCode.h"

NSString* const MUKErrorDomain = @"MUKErrorDomain";

NSString* const MUK_EXTM3U = @"#EXTM3U";
NSString* const MUK_EXT_X_VERSION = @"#EXT-X-VERSION:";
NSString* const MUK_EXT_X_STREAM_INF = @"#EXT-X-STREAM-INF";

/// 4.3.2.1. EXTINF
NSString* const MUK_EXTINF = @"#EXTINF:";
/// 4.3.2.2. EXT-X-BYTERANGE
NSString* const MUK_EXT_X_BYTERANGE = @"#EXT-X-BYTERANGE:";
/// 4.3.2.3. EXT-X-DISCONTINUITY
NSString* const MUK_EXT_X_DISCONTINUITY = @"#EXT-X-DISCONTINUITY";
/// 4.3.2.4. EXT-X-KEY
NSString* const MUK_EXT_X_KEY = @"#EXT-X-KEY:";
/// 4.3.2.5. EXT-X-MAP
NSString* const MUK_EXT_X_MAP = @"#EXT-X-MAP:";
/// 4.3.2.6. EXT-X-PROGRAM-DATE-TIME
NSString* const MUK_EXT_X_PROGRAM_DATE_TIME = @"#EXT-X-PROGRAM-DATE-TIME:";
/// 4.3.2.7. EXT-X-DATERANGE
NSString* const MUK_EXT_X_DATERANGE = @"#EXT-X-DATERANGE:";

/// 4.3.3.1. EXT-X-TARGETDURATION
NSString* const MUK_EXT_X_TARGETDURATION = @"#EXT-X-TARGETDURATION:";
/// 4.3.3.2. EXT-X-MEDIA-SEQUENCE
NSString* const MUK_EXT_X_MEDIA_SEQUENCE = @"#EXT-X-MEDIA-SEQUENCE:";
/// 4.3.3.3. EXT-X-DISCONTINUITY-SEQUENCE
NSString* const MUK_EXT_X_DISCONTINUITY_SEQUENCE = @"#EXT-X-DISCONTINUITY-SEQUENCE:";
/// 4.3.3.4. EXT-X-ENDLIST
NSString* const MUK_EXT_X_ENDLIST = @"#EXT-X-ENDLIST";
/// 4.3.3.5. EXT-X-PLAYLIST-TYPE
NSString* const MUK_EXT_X_PLAYLIST_TYPE = @"#EXT-X-PLAYLIST-TYPE:";
/// 4.3.3.6. EXT-X-I-FRAMES-ONLY
NSString* const MUK_EXT_X_I_FRAMES_ONLY = @"#EXT-X-I-FRAMES-ONLY";

NSString* const MUK_EXT_X_KEY_METHOD_NONE = @"NONE";
NSString* const MUK_EXT_X_KEY_METHOD_AES_128 = @"AES-128";
NSString* const MUK_EXT_X_KEY_METHOD_SAMPLE_AES = @"SAMPLE-AES";
